# Generated by Django 3.0.1 on 2020-03-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time', models.DateField()),
                ('image', models.BinaryField(blank=True)),
                ('video', models.TextField(blank=True)),
            ],
        ),
    ]
