# Generated by Django 3.0.1 on 2020-03-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex_design_backend', '0002_auto_20200316_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='./images/'),
        ),
    ]
